name: vidify-desktop
type: app
version: '2.2.3'
summary: Vidify
description: |
    Watch music videos in real-time for the songs playing on your device
icon: 'vidify/gui/res/icon.svg'
# license: LGPL-3.0-or-later
confinement: strict

apps:
  vidify:
    command: vidify

parts:
  vidify:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      # Main dependencies
      - python3-pyqt5
      - python3-appdirs
      - python3-pydbus
      - youtube-dl
      # Mpv is used by default because it's lighter and works better
      # with the audiosync feature.
      - libmpv-dev
      # GLib
      - libglib2.0-dev
      # PyGobject
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - libcairo2-dev
      # Audiosync support
      - libfftw3-dev
      - libpulse-dev
      - ffmpeg
    python-packages:
      # Qt-related
      - qtpy
      - PyQtWebEngine
      - qdarkstyle
      # Mandatory
      - python-mpv
      - lyricwikia
      - tekore
      # Optionals
      - vidify-audiosync
      - zeroconf
